### ISSUE TITLE
ld: library not found for -lrt

### ISSUE THREAD

**Issue by Maryom** [lh3/bwa#173]
Hi,

Thanks for your useful repo.

I need to use [SparkBWA](https://github.com/citiususc/SparkBWA) and I got the following error:

```
1 warning generated.
make -C ./bwa-0.7.15
make[1]: Nothing to be done for `all'.
if [ ! -d "build" ]; then mkdir build; fi
cp ./bwa-0.7.15/*.o build
gcc -shared -o build/libbwa.so build/*.o -lrt -lz
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libbwa.so] Error 1
[ERROR] Command execution failed.
```

Do you know what is the problem ? it's from BWA or from SparkBWA or from my MacBook because I'm using macOS high sierra and I communicated with SparkBWA owner and he told me he never runs it on macOS.

Thanks.

Best regards,
Mariam AlJamea

**Comment by lh3** [comment]
This seems specific to sparkbwa. Anyway, you can remove "-lrt" in Makefile, or manually type the following:
```sh
gcc -shared -o build/libbwa.so build/*.o -lz
```
in the right directory.

**Comment by Maryom** [comment]
Thanks for your reply. I don't think it related to sparkbwa because I got the same error when I tried to run [BigBWA](https://github.com/citiususc/BigBWA) I think it related to macOS, Do you have any ideas how to solve it ?

when I removed `"-lrt" in Makefile` I got this error:

```
gcc -shared -o build/libbwa.so build/*.o 
Undefined symbols for architecture x86_64:
  "_gzclose", referenced from:
      _bamlite_gzclose in bamlite.o
      _main_maxk in maxk.o
      _err_gzclose in utils.o
     (maybe you meant: _bamlite_gzclose, _err_gzclose )
  "_gzdopen", referenced from:
      _bamlite_gzopen in bamlite.o
      _main_mem in fastmap.o
      _main_maxk in maxk.o
      _main_pemerge in pemerge.o
      _err_xzopen_core in utils.o
  "_gzerror", referenced from:
      _bamlite_gzread in bamlite.o
      _kseq_read in utils.o
      _ks_getuntil2 in utils.o
      _err_gzread in utils.o
  "_gzopen", referenced from:
      _bamlite_gzopen in bamlite.o
      _main_maxk in maxk.o
      _main_pemerge in pemerge.o
      _err_xzopen_core in utils.o
     (maybe you meant: _bamlite_gzopen)
  "_gzread", referenced from:
      _bamlite_gzread in bamlite.o
      _kseq_read in utils.o
      _ks_getuntil2 in utils.o
      _err_gzread in utils.o
     (maybe you meant: _err_gzread, _bamlite_gzread )
  "_zError", referenced from:
      _bamlite_gzclose in bamlite.o
      _err_gzclose in utils.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libbwa.so] Error 1
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:08 min
[INFO] Finished at: 2018-01-17T17:32:12+03:00
[INFO] Final Memory: 16M/76M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (makeBwa) on project SparkBWA: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by lh3** [comment]
Don't remove "-lz". If you have more questions, ask sparkbwa. It is really their problems.

**Comment by Maryom** [comment]
Thank you so much @lh3 removing "-lz" solved my problem.

I finally got:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16:12 min
[INFO] Finished at: 2018-01-17T18:05:36+03:00
[INFO] Final Memory: 18M/75M
```

I really appreciate your help 🙏🏼
